apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux
spec:
  interval: 5m
  targetNamespace: keycloak
  chart:
    spec:
      chart: ./keycloak
      sourceRef:
        kind: GitRepository
        name: keycloak-auth-demo
        namespace: flux
      interval: 1m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3