apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux
spec:
  interval: 10s
  releaseName: keycloak
  targetNamespace: keycloak
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: GitRepository
        name: keycloak-auth-demo
        namespace: flux
      valuesFiles:
        - keycloak/values.yaml
        - keycloak/overridden-values.yaml
  install:
    createNamespace: true