apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ui-components
  namespace: flux-system
spec:
  interval: 10m
  path: ./infra/ui
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m
  force: false
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ui-deployment
      namespace: default
  postBuild:
    substitute:
      ENVIRONMENT: production
  validation: client