apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-ui-service
  namespace: k8s-demo-app
  labels:
    app: k8s-demo-ui
spec:
  selector:
    app: k8s-demo-ui
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000