apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: reviews-route
  namespace: k8s-demo-app
spec:
  hosts:
  - k8s-demo-ui-service.k8s-demo-app.svc.cluster.local
  gateways:
  - main # expose the ui external to the cluster
  http:
  - match:
    - uri:
      prefix: "/"
    route:
    - destination:
      host: k8s-demo-ui-service
      port:
        number: 3000
    timeout: 15s
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes