proxyHeaders: "forwarded"

auth:
  existingSecret: "admin-password"
  passwordSecretKey: "password"
  adminUser: admin

production: false

configuration: |-
  hostname=keycloak.local
  hostname-url=https://keycloak.local
  hostname-admin-url=https://keycloak.local
  http-enabled=true
  proxy=passthrough