apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-api-service
  namespace: k8s-demo-app
spec:
  selector:
    app: k8s-demo-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP