apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  template:
    metadata:
      annotations:
        # Select the gateway injection template (rather than the default sidecar template)
        inject.istio.io/templates: gateway
      labels:
        # Set a unique label for the gateway. This is required to ensure Gateways can select this workload
        istio: ingressgateway
        # Enable gateway injection. If connecting to a revisioned control plane, replace with "istio.io/rev: revision-name"
        sidecar.istio.io/inject: "true"
    spec:
      # Allow binding to all ports (such as 80 and 443)
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "0"
      containers:
        - name: istio-proxy
          image: auto
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 1337
            runAsGroup: 1337
          volumeMounts:
            - name: ingressgateway-certs
              mountPath: /etc/istio/ingressgateway-certs
              readOnly: true
            - name: ca-cert
              mountPath: /etc/istio/ca-cert
              readOnly: true
      volumes:
        - name: ingressgateway-certs
          secret:
            secretName: istio-ingressgateway-certs
        - name: ca-cert
          secret:
            secretName: ca-cert
---
apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: NodePort
  selector:
    istio: ingressgateway
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080 # This will be exposed on the Kind node
      name: http
    - port: 443
      targetPort: 8443
      nodePort: 30443
      name: https
---

apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVsVENDQW4yZ0F3SUJBZ0lVVTJwbm03QzlUT0JPQVNTendybUxYUkM5MGtjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VURVBNQTBHQTFVRUF3d0dVbTl2ZEVOQk1CNFhEVEkxTURFd01qQTFNREV6TlZvWERUSTJNREV3TWpBMQpNREV6TlZvd2J6RUxNQWtHQTFVRUJoTUNWVk14RGpBTUJnTlZCQWdNQlZOMFlYUmxNUTB3Q3dZRFZRUUhEQVJECmFYUjVNUlV3RXdZRFZRUUtEQXhQY21kaGJtbDZZWFJwYjI0eEVUQVBCZ05WQkFzTUNFOXlaeUJWYm1sME1SY3cKRlFZRFZRUUREQTVyT0hNdFpHVnRieTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQwpBUW9DZ2dFQkFOdnN2NnlRWjFKQzVBam81YzRjc0hVdFFkN0R6U2hLR0NYR1MzVU5hUk9xS2lFcnU0TXBjcnVWCmNqU0J6My8vdXUvbEV2Q0Z5bmpPNWM5UzQ0T1I3TldBd1JvMGZRa3NwT01yZGJNMnI4ZlZNQXFDZ1V6Wml6VmkKc2lSM2kwQ3NVdGtYUUFoTk9acDVuMkdCbk5GY3hzTzkzNDZGK1FmK0NmWUVhdTNXTk92VDhSVWp6WmRDVTUzNQpOLzhTTFhzOHQvQU9pc0lsOHRnYkpPWUcxSVVKdEgvY2pIby9pSTRmVGlhYnJWTWZvVDBDcTRMZ09xM1FEQ2U1CjRLV3hpZkdVYkZpRVF0dVcxVXplVkZkRkc4VFEvS24xU2dkRDFhSHFxaHJSd1JuYlBreDBzREVHaVBZbDFITGYKYm9ZUWFYM3BHeHVFN1RpTDR1dytGaDZVNEtKRU1rRUNBd0VBQWFPQmhqQ0JnekFKQmdOVkhSTUVBakFBTUFzRwpBMVVkRHdRRUF3SUY0REFwQmdOVkhSRUVJakFnZ2c1ck9ITXRaR1Z0Ynk1c2IyTmhiSUlPYTJWNVkyeHZZV3N1CmJHOWpZV3d3SFFZRFZSME9CQllFRk9BS3dUdEFJVWpwL3FLQ1VWeGtMNWh1UjAvNk1COEdBMVVkSXdRWU1CYUEKRkkrUE92R0ZMeDRsOSs2c3BVUHY0L1BBcTZCY01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQjZsajJCazUyRwp6QnlWc0gyVXV0bithdmUzZlUzb0NvdUlmZmFRVFdxcVpxK0JYSnJmNUFjWGpEb0kvbm1Yd1hNYmpxb1JDVzNoCmIwQ0VQMmdoSE9MQWptQU9NZkRWVndQdEFJL2NLeW1jOGZkWVlsSzYyTmVzWElIU2JQQXRvb0ZTTjBNVzVKYmkKVGt2ZzBXeGwzWWxMd3VFemJBcU1NcUYwVk0zbFdTUUhqY01ETTNiT3N1THp3ZWVsZjloeHVFbWZwTEkrOTJwLwo5N3JZcGtheTNRd3NJZkszOUxIOGtXeldPVVZMRHF0aFFjMVpFRVVIWFRjaGlrUzF5MmNackpkNDNxTFl6cW9iClpZMnRPM1VhMkRmMTV0alNFNDF3U0xoLzZKM0hVVFE0NDlaMnBGU2ZvT0t6d2NwN2NRVmVKMitKNnBFM015dksKWm5LSUFObVBhVUlLaVBOTjdNZ1hZTjJwSVhSUjZneFUyMUFLUzVlQ2VYZGIxTmRxSTBnLzlvMk5hWFVsRTh4WApycnF1dkhTbVY3WitXeFFKLytGZU5TQjhUc3dOaHhvM3VkTWY0bmpxQU1SbDhtR29sUXY4R1gwNmVnblkyQUVpCmFUL3hqK3p4N2JrVXlTSkc4ZmFQZUliQU1lY2diYlB2dE9HbERRcnY0cEpSdUlVUmQybVhxWEpqalpGZFBwb1IKQys1SWlsemZvRWZIbXNDc0cwZGI0b29JS0FaQlhJc2s4MnhJTlQxNHB6VmsrLy9mSllxMzBvMkJwL0xZRFVwYQpDT3pvNjJjQU9HeGxVZHhJUmlKQmQva2g0ekUxbEVPd3VuTVVkZ3haYnJEYVNFTXFETzJZT0RxenJ1ZGFBSGt1CkhYQXF2L05Qd2RabjQyTS9VcFA3bm1mWWV2UitiR1lEbWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRGI3TCtza0dkU1F1UUkKNk9YT0hMQjFMVUhldzgwb1NoZ2x4a3QxRFdrVHFpb2hLN3VES1hLN2xYSTBnYzkvLzdydjVSTHdoY3A0enVYUApVdU9Ea2V6VmdNRWFOSDBKTEtUakszV3pOcS9IMVRBS2dvRk0yWXMxWXJJa2Q0dEFyRkxaRjBBSVRUbWFlWjloCmdaelJYTWJEdmQrT2hma0gvZ24yQkdydDFqVHIwL0VWSTgyWFFsT2QrVGYvRWkxN1BMZndEb3JDSmZMWUd5VG0KQnRTRkNiUi8zSXg2UDRpT0gwNG1tNjFUSDZFOUFxdUM0RHF0MEF3bnVlQ2xzWW54bEd4WWhFTGJsdFZNM2xSWApSUnZFMFB5cDlVb0hROVdoNnFvYTBjRVoyejVNZExBeEJvajJKZFJ5MzI2R0VHbDk2UnNiaE8wNGkrTHNQaFllCmxPQ2lSREpCQWdNQkFBRUNnZ0VBRXV6dDlyUHJqRWJ3MkRwd2tqcmlUWWNpUU1FUlRkc0lkbkc0eXg4bkVIZm4KamJpMWQzMVE0QWNsajVLdk1GanB0Wnk5TTBFVU1pNjkxSWhSeDEvK3BVWGgrRGNWbm4wK3lFVFVhV0oyb0lmKwpUUjA3Y3NsU3d6cVYwWEVQSlBiZlgwcXlxalE1Rll2TFZTa0IvWHRTS0lTVnNTNWl4cGNNTk9WZTdVNHVlaSszCldJSVhxZ0FFa0w2MXIrbHcwWTJFVkNxUmt0OFRUWktqU3pFTVEzYkVrNGtlYXdzQTlHNEgyaGE0Y1NoVTd2TW0KRkM4YnZmL1pIL09MTGVtSUhFRzcwZWN5RGI4alhGelRnVjdXQUpYU2lXTkJyclA1MUR0dmdXT1NCT09Rd1pybgowdzZwak45UldheUZrWkhyUFc1L3NLQ3lBVXNoZC9zNmR2TVpIY0hTRVFLQmdRRHppemZEMmhpTDlLcWxBWlFGClh1VTR0ZDdybjNHT2ROZGl0eGtwRHdVY09YL2NzbGtXMVJET3hJR3BKSngyYTIya3c3M1BKZ2o0blI1eW5RZXYKVWVGM3FPYlBuWmpsdVkzTlpwYitGUlBVbEpCa2NHRm10dmFuWDI0UmtoUlpzQjZEaXpETy90eEhOdEdWcnVMRgpCR1RtdWxMWnFLWVRtajNFY29NaW9OWlBTUUtCZ1FEbkxFZnRMdCtiTmVoamFlMitIdGlIZzY0eXFaMVFUbTZ4CnM4OC9iV1JiNDcwb2hEWjRkM1JTYXJ2emdYRlFETk9RWWd5clV2VzQ3OFJnL3psRTdpcVZTYyt0citVSWpXcWMKWVFWNmt0ZnJ5REVMWngvMTlnMEZzNmh2cDNxOXYxQ3lUblNwYy9sWVdtcDFaTWVLcDBMRU11RFJqUm1VTnZrQQpnNjNKTGJrek9RS0JnRTVwQ0M4NlRLVGl4UDRUSUFFS3FHbzF3K3ZBamVMN28welkvblRGclRPRkg3R0Npa1JiCm5PbTFRcm1lVy9HVWJOeWJXTVVVemRhZFgyd3ZPb1lycXBmSC9XZmlxWk5zeGtiWFBNM1pJMlZSMzVzMncyVTYKaXZjZ05tUFowRXQvOUpNTmdVMWpxTEFVNmkxeS9QZkpqbUxxb2pvSm5rNjVYaUdkYkxMOWJZSmhBb0dBVENteQpxTnBBb1lwcFBoZXdWR3NsTzhDT3EvSmwrZ2RkUVA3VTBUamhUOFVBbFZDNkFZYVp0RzJsN3R3KzBQam8yekR5CnE1OXhoYlM1SnB2djZsM3RlYklQMGxHWlMvQUxwK252UENzVktJR1Vad1ZhNmxaZWcvcGxEQ1JKdENwTUUvTDEKVEw4QTc3TWFVQU1jR3Zwd2JPTzJYbFAya1hackkxZys4WUUyKzBFQ2dZRUFsZWdWVk1hQXJ5aERSWnpqNlpuRApQeUZBM0czekZiMlhBT2NLUnRqZ2R2OTRXTjFsbk1nTXpSSit2OVozVngrVUZDWGhjYXorSDFXaUo3ZWlhK3RXCndyZUF3VFRuL2xSRVU3WFlSR3FYR21zb2RPTVIrQWF0L3RpVlNPNHpPM2JSejNrd09CR0FsbjVoYUZKY0h6ZzQKa2FLUmVVdUxZVjgyb05qZzBjREpwOHM9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system

---

apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZBekNDQXV1Z0F3SUJBZ0lVVzRCVkV3MDh1V3R1Zkk5c0NicVB2RlROWjdvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VURVBNQTBHQTFVRUF3d0dVbTl2ZEVOQk1CNFhEVEkwTVRJeU5ERTVNRFF4TVZvWERUSTFNVEl5TkRFNQpNRFF4TVZvd0VURVBNQTBHQTFVRUF3d0dVbTl2ZEVOQk1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBCk1JSUNDZ0tDQWdFQW9HdnFTMmoxUnU0Q29KbUVpQkdRWmJ1UGUwOGYvZGIzQ2FITlA2cFdkaWZYaXA2QkhLL0oKZ0hqbnNzWElKVEhERHkya1doWnFkSmxXdTRnNzJtd0dKL3BpVktwMmptQVcwMkxPSnFsZG5ObG9vVUtxOFJOTgpsaXdhdmhnZUhGNDRZRm9jT28vMFd3RFQrUjl0ZEI5UmJSUmdpa0cvRkVkTnhBM2JXNTErUXpoTVpMSFM4Q1ZICm1sNjdKUGJGcm14WFBwcUtNZ244UGpyYzFMaXJodkp2Qnd0TE5NbkVVUTZrSDhhKzB2eUpZUkVSaWlaYkl6dkgKYWxiakUxK1YyNU9PbE9wc21LUVpwMnluMVRBZTJDRzR5S2ZjR1oyT1FHdE8vcC95UDNqUjFOa0Y5ZDUybFRaQgovQUtHRWVLb0hKaCtBRkx4VU9OQjRDUk41V0NNenV1OHhRREVxNGgydUdRK3Jad3dZT0xKVXAyYWp2ZUZxSzRNCkpMcVk1MWg1VjdvaVVHazhzR2NMcHZ1WVFIa01vcTdiR0Q2Y3c2SXIrUVc3VmwxaCt1ZjZLSFJpRTRHV3NGYmcKd3BxdnQzN1NzU2FGMDlTVU9QcmVKeUxON00zbkQ5aFBCZHBtTU4wakQ1endqT0ZKTmFMYjVrRGduaWl5aVJZRgppOWpHZ2tHMi9rd3FOdjBDTE9BbDd3VFR2NzhVZTYvYllTWUVhWHc0RE9HOUdYODNaRUhRUWVLVlg2TnZ3QTM3CkpTMXY2bFB3eXNYdUk5cTVrNVZIVnpvajZRdjgxMGZBT0ZPaGxXVVpnUks4dXRZRWlEeEhuY2VwKzFVdVBnS2UKZFV0V3A5eFI3c1dPWUg4UUVFcWs3SXJEUFpiRE1NeVVtT1F6cGxZeTRBN3BnbmgvSDJML3NMTUNBd0VBQWFOVApNRkV3SFFZRFZSME9CQllFRkkrUE92R0ZMeDRsOSs2c3BVUHY0L1BBcTZCY01COEdBMVVkSXdRWU1CYUFGSStQCk92R0ZMeDRsOSs2c3BVUHY0L1BBcTZCY01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUwKQlFBRGdnSUJBSmd4Nm5WTTlhR1o3TERiS1NySC85VzNtbzdvSUxwOGx1a2o4SGM4Y3lveE9RZ1JYTktFcCtweApwUGNLYlpibWtrWkF6VWxLT2IyOHdESy9GWmNid2FiUXhHNkdaSmpnNldGR01tTzZxbmtsVXYzc1NGemVkVk1aCjl5L3Zqdk1seVFpNWRVWE50YzN6QVNJZ00xSXMzR2lKdmJ2OGIzS212dTVObis1aXo2dm0wNW0yZGZXWTFkc20KY0c1Qmp2Mi94cU1sYmRnQmtVMUVScGtEbXRsN0lBMkdDemRqNHVpOUNmUkNzdHFtY3YrUExEUFA3UkxsNnpUcQo0cjZYSEVLQ0gzZGFXWk00UEwxNzlvTm5kdHFtdGJyTGdKQzRENTlVaFY5RUhuMDI2RVp2QXZoRkRWRkhpVXJjClV5eTJUc3hOSHhqOUtiNC84RC9XczlVb3B0WEJUalBvN0t5QW5sZnhBdCt3VmVTaDdvSktkdk1DenFmbjdManoKdm00N2RWQ2U3Yjc4dFVqRVpGUzdxR3N1SGt0YXVLcTArRGdmcndNYjZvRS9mdDRicFR5Z3B6amVscXd3RE8yaAp6MHpHczBmN3JXNEdPU1d4UjNIUTJkWGdDNG1IV3pWYUNWWFRsengraUd6VEgxRnBJOTJzcWZ3Qll1TUpRYWI4CnJVcTJsNTZHR0lkdmcrdVBqSk0yTldVVHFScDkrMEtBM0Z6dE02RWl5V25QaGRXaDB4UElrZ0hzRFlIRGhlQWIKWk81OWltQ0pXZTViL3l1ejkxMURxU0dKYzRJbks2K0hWRjBWdXl4RFNZRHBXdjdQRkJ1cnVYcFZYZUlwNVpGQQpmK0Vsa1JFMVdiS1hsbXg0VWp6dkNIenJuWmE4aHozcmNyajljQURWWlpUdWV1R1VvSWpECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  name: ca-cert
  namespace: istio-system
  
---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: main
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # Use the default Istio ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*" # Accept requests from any host
      tls:
        httpsRedirect: true # Redirect HTTP to HTTPS
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*" # Accept requests from any host
      tls:
        mode: SIMPLE
        serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
        privateKey: /etc/istio/ingressgateway-certs/tls.key
        caCertificates: /etc/istio/ca-cert/ca.crt
