apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: keycloak-virtual-service
  namespace: keycloak
spec:
  hosts:
    - keycloak.local
  gateways:
    - istio-system/main # expose the ui external to the cluster
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: keycloak
            port:
              number: 80
          headers:
            request:
              set:
                # these must be set to ensure that Keycloak serves content and URLs with HTTPS
                # TLS terminates at the Istio gateway, so we need to tell Keycloak
                # that the traffic is 443 traffic... if we do not set this, Keycloak will not load due to mixed-content (Keycloak will generate URls and resources with http prefixes)
                x-forwarded-proto: https
                x-forwarded-port: "443"
                x-forwarded-host: keycloak.local
                forwarded: "proto=https;host=keycloak.local"
      timeout: 15s
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
